In [2]:
import torch
import numpy as np

## Creating tensors from data

In [4]:
data = [[1,2],[3,4]]
tensor_1 = torch.tensor(data)
print(tensor_1)
print(type(tensor_1))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [7]:
data = [[1.0,2.0],[3.0,4.0]]
tensor_1 = torch.tensor(data)
print(tensor_1)
print(type(tensor_1))

tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>


In [5]:
data = [[1,2],[3]]
tensor_1 = torch.tensor(data)
print(tensor_1)
print(type(tensor_1))

ValueError: expected sequence of length 2 at dim 1 (got 1)

In [6]:
data = [['a','b'],['c','d']]
tensor_1 = torch.tensor(data)
print(tensor_1)
print(type(tensor_1))

ValueError: too many dimensions 'str'

In [8]:
data = [[1,2],[3,4]]
data_array = np.array(data)
tensor_1 = torch.from_numpy(data_array)
print(tensor_1)
print(type(tensor_1))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


## Creating tensors from built in functions

In [55]:
x_ones = torch.ones_like(tensor_1)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [56]:
x_rand = torch.rand_like(tensor_1,dtype=torch.float)
x_rand

tensor([[0.3174, 0.5748],
        [0.3749, 0.7914]])

In [57]:
shape = (3,2)

In [58]:
print(torch.zeros(shape))
print(torch.ones(shape))
print(torch.rand(shape))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.4303, 0.4037],
        [0.6872, 0.0937],
        [0.4227, 0.7456]])


In [59]:
random_tensor = torch.rand(2,3)

In [60]:
print(random_tensor)

tensor([[0.9441, 0.7370, 0.1923],
        [0.7571, 0.7995, 0.2816]])


## Attributes of tensors

In [61]:
print(random_tensor.shape)
print(random_tensor.dtype)
print(random_tensor.device)

torch.Size([2, 3])
torch.float32
cpu


## Shifting tensor to GPU if available

In [63]:
if torch.cuda.is_available():
    random_tensor = random_tensor.to('cuda')

In [64]:
random_tensor.device

device(type='cuda', index=0)

## Slicing and indexing in tensors

In [66]:
random_tensor[:,1]

tensor([0.7370, 0.7995], device='cuda:0')

In [67]:
random_tensor[:2,1:2]

tensor([[0.7370],
        [0.7995]], device='cuda:0')

## Assigning values to slice of tensors

In [68]:
random_tensor[:,2] = 0

In [69]:
random_tensor

tensor([[0.9441, 0.7370, 0.0000],
        [0.7571, 0.7995, 0.0000]], device='cuda:0')

## Concatenating tensors

### Along the x axis

In [72]:
t1 = torch.cat((random_tensor,random_tensor),dim=1) # Horizontal stack
print(t1)

tensor([[0.9441, 0.7370, 0.0000, 0.9441, 0.7370, 0.0000],
        [0.7571, 0.7995, 0.0000, 0.7571, 0.7995, 0.0000]], device='cuda:0')


### Along the y axis

In [73]:
t1 = torch.cat((random_tensor,random_tensor),dim=0) # vertical stack
print(t1)

tensor([[0.9441, 0.7370, 0.0000],
        [0.7571, 0.7995, 0.0000],
        [0.9441, 0.7370, 0.0000],
        [0.7571, 0.7995, 0.0000]], device='cuda:0')


## Operations on tensors

### Addition

In [76]:
random_tensor+random_tensor

tensor([[1.8881, 1.4740, 0.0000],
        [1.5143, 1.5990, 0.0000]], device='cuda:0')

### Subtraction

In [77]:
random_tensor-random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

### Scalar multiplication

In [80]:
random_tensor*3

tensor([[2.8322, 2.2110, 0.0000],
        [2.2714, 2.3985, 0.0000]], device='cuda:0')

### Matrix multiplication

In [81]:
random_tensor@random_tensor.T

tensor([[1.4344, 1.3040],
        [1.3040, 1.2124]], device='cuda:0')

In [83]:
random_tensor.matmul(random_tensor.T)

tensor([[1.4344, 1.3040],
        [1.3040, 1.2124]], device='cuda:0')

### Dot product

In [85]:
random_tensor*torch.rand_like(random_tensor)

tensor([[0.7958, 0.2294, 0.0000],
        [0.4102, 0.7430, 0.0000]], device='cuda:0')

### In place operations

In [86]:
random_tensor.add_(3)

tensor([[3.9441, 3.7370, 3.0000],
        [3.7571, 3.7995, 3.0000]], device='cuda:0')

In [91]:
random_tensor.copy_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

## Comparison with numpy

In [94]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [95]:
t.add_(4)

tensor([5., 5., 5., 5., 5.])

In [96]:
n

array([5., 5., 5., 5., 5.], dtype=float32)