In [1]:
import torch

## requires_grad arguments initiates gradient calculation

In [2]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.rand(5,3,requires_grad=True)
b = torch.rand(3,requires_grad=True)
z = torch.matmul(x,w) + b

In [10]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [13]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.rand(5,3)

In [14]:
w.requires_grad_(True)
b = torch.rand(3,requires_grad=True)
z = torch.matmul(x,w) + b

In [15]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
print(loss)

tensor(3.1284, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [18]:
print(f"Gradient for z = {z.grad_fn}")
print(f"Gradient for loss = {loss.grad_fn}")

Gradient for z = <AddBackward0 object at 0x0000024B5816E4D0>
Gradient for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000024B58336080>


In [29]:
loss

tensor(3.1284, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [30]:
w,b

(tensor([[0.1848, 0.7845, 0.4071],
         [0.6665, 0.9389, 0.6353],
         [0.8357, 0.5713, 0.1148],
         [0.8460, 0.6167, 0.1674],
         [0.4101, 0.6754, 0.1546]], requires_grad=True),
 tensor([0.8276, 0.1057, 0.2289], requires_grad=True))

In [31]:
loss.backward()
print(loss)

tensor(3.1284, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [32]:
w.grad,b.grad

(tensor([[0.3258, 0.3252, 0.2822],
         [0.3258, 0.3252, 0.2822],
         [0.3258, 0.3252, 0.2822],
         [0.3258, 0.3252, 0.2822],
         [0.3258, 0.3252, 0.2822]]),
 tensor([0.3258, 0.3252, 0.2822]))

## To disable gradient tracking

In [35]:
with torch.no_grad():
    z = torch.matmul(x,w) + b
print(z.requires_grad)

False
